### ISSUE TITLE
Estimated cost of "do" operator in contextual menu

### ISSUE THREAD

**Issue by jorgeramirez** [TrentoCrowdAI/servant-api#39]
This estimated cost section will show the estimated cost in F8 and Toloka. A "Compute cost" button triggers the cost estimation feature, and after it renders the estimated costs one can recompute the estimations if there is any change in the parameters of the do operator.

**Comment by simonedegiacomi** [comment]
It is possible to get the estimated cost in Toloka using this endpoint:
`https://sandbox.toloka.yandex.com/api/new/requester/pools/${poolId}/analytics?fields=expectedBudget`.
I didn't find a way to get the estimated cost on F8 yet.

**Comment by jorgeramirez** [comment]
Maybe this link helps
https://success.figure-eight.com/hc/en-us/articles/115000832063-Frequently-Asked-Questions
